//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_MeterSampleList
    {
        public System.Guid Id { get; set; }
        public System.Guid MeterSampleBillId { get; set; }
        public System.Guid ClothType { get; set; }
        public string ClothTypeName { get; set; }
        public Nullable<System.Guid> ColourId { get; set; }
        public string Colour { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> GramWeight { get; set; }
        public decimal Length { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
