//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_User
    {
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string UserCnName { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Age { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.Guid> Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
