//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MeterSampleList
    {
        public System.Guid Id { get; set; }
        public System.Guid CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public bool IsPayment { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.Guid> ClothType { get; set; }
        public string ClothTypeName { get; set; }
        public Nullable<System.Guid> ColourId { get; set; }
        public string Colour { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> GramWeight { get; set; }
        public Nullable<decimal> Length { get; set; }
    }
}
