//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZyfTestDbEntities : DbContext
    {
        public ZyfTestDbEntities()
            : base("name=ZyfTestDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_ClothYard> B_ClothYard { get; set; }
        public virtual DbSet<B_ClothYardPaymentRecord> B_ClothYardPaymentRecord { get; set; }
        public virtual DbSet<B_ClothYardWeightList> B_ClothYardWeightList { get; set; }
        public virtual DbSet<B_Customer> B_Customer { get; set; }
        public virtual DbSet<B_Dictionary> B_Dictionary { get; set; }
        public virtual DbSet<B_DictionaryType> B_DictionaryType { get; set; }
        public virtual DbSet<B_Menu> B_Menu { get; set; }
        public virtual DbSet<B_MeterSampleBill> B_MeterSampleBill { get; set; }
        public virtual DbSet<B_MeterSampleList> B_MeterSampleList { get; set; }
        public virtual DbSet<B_Role> B_Role { get; set; }
        public virtual DbSet<B_RoleMenu> B_RoleMenu { get; set; }
        public virtual DbSet<B_RoleType> B_RoleType { get; set; }
        public virtual DbSet<B_SN> B_SN { get; set; }
        public virtual DbSet<B_User> B_User { get; set; }
        public virtual DbSet<B_UserRole> B_UserRole { get; set; }
        public virtual DbSet<B_UserToken> B_UserToken { get; set; }
        public virtual DbSet<D_BaseCloth> D_BaseCloth { get; set; }
        public virtual DbSet<D_Factory> D_Factory { get; set; }
    }
}
